spring:
  datasource:
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://127.0.0.1:3306/yu?useUnicode=true&characterEncoding=UTF-8&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=false
   username: root
   password: 123456
  jpa:
   show-sql: true ## 查询时是否显示Sql语句，在生成环境禁用
   generate-ddl: true ## 字符创建表结构
   database-platform: org.hibernate.dialect.MySQL5Dialect
   hibernate:
    use-new-id-generator-mappings: true
    ddl-auto: update ## 自动升级表结构
